### PR TITLE
Display placeholder even if there is an initial value.

### PR DESCRIPTION
**Pull request by angelozerr**
Display placeholder even if there is an initial value.

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
As I don't understand why placeholder is generated only if there is not an initial value, I create this PR. IMHO placeholder should be generated every time. 

For instance if your textbox has no initial value, placholder is displayed, if you fill it, placeholder content disapear, if you remove content, placeholder is displayed. To be consistent with this behavior, the case when textbox has an initial value should generate a placeholder.

**Comment by angelozerr** [comment]
@jeffmaury are you OK to merge this PR?

**Review by jeffmaury — APPROVED** [review]
LGTM

**Comment by angelozerr** [comment]
Thanks @jeffmaury

**Pull request merged**
