### PR TITLE
Fix h2 -> span and error message alignment.

### PR DESCRIPTION
**Pull request by sudhirverma**
Screenshot 2022-04-11 at 6 56 35 PM

cc: @mohitsuman

### CODE REVIEW

**Comment by jeffmaury** [comment]
That may break existing extensions. WDYT @robstryker

**Comment by mohitsuman** [comment]
We also need to fix the text alignment and text box. The alignment is broken if we view in small screen.

For reference.

Screenshot 2022-04-11 at 9 55 21 PM

**Comment by robstryker** [comment]
Patch is good generally but it doesn't fix this issue, which isn't visible on all color themes:

image

**Comment by sudhirverma** [comment]
adding screen screenshot 
Screenshot 2022-04-12 at 2 56 11 AM

**Pull request merged**
